[package]
name = "rust-discord-voice"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
reqwest = { version = "0.12.8", features = [ "blocking" ] }
serde_json = "1.0.128"
simple_logger = "5.0.0"
